package ca.uwaterloo.cs.sgp.conversion;

import java.util.HashMap;

/**
 * Created by anilpacaci on 2018-05-21.
 * this class is created to convert graph in adj list format to METIS Competible format
 * METIS requires ID's to be in consecutive range [1..N]
 * This class uses the lookup files generated by snap2metis script by Spark
 */
public class Adj2MetisIdConverter {

    HashMap<Long, Long> lookupMap;



    public static void main(String[] args) {

    }

}
